import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/Appbar";
import Sidebar from "@/components/Sidebar";
import "../components/Sidebar.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="{inter.className}">
        <Appbar />
        <div className="panel display basis-auto">
          <Sidebar className="basis-auto w-1/5"/>
          {children}
        </div>
      </body>
    </html>
  );
}
